# database connection
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3309/timebench'
    username: 'timebench'
    password: 'timebench'
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  data:
    mongodb:
      database: commons-rest-sample
# json configuration
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: true
    default-property-inclusion: non_null