# database connection
spring:
  datasource:
    url: 'jdbc:h2:mem:testdb'
    username: 'sa'
    password: 'password'
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  data:
    mongodb:
      database: commons-rest-sample
  # json configuration
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: true
    default-property-inclusion: non_null