language: java
jdk:
  - openjdk8
services:
  - mongodb
## gpg stuff
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

# code climate configure
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
## default build
script: mvn --settings .travis/settings.xml -U clean install
# code climate upload coverage
after_script:
  - JACOCO_SOURCE_PATH=commons-rest/commons-rest-api/src/main/java ./cc-test-reporter format-coverage -t jacoco -o coverage/codeclimate.rest-api.json commons-rest/commons-rest-api/target/site/jacoco/jacoco.xml
  - JACOCO_SOURCE_PATH=commons-rest/commons-rest-server/src/main/java ./cc-test-reporter format-coverage -t jacoco -o coverage/codeclimate.rest-server.json commons-rest/commons-rest-server/target/site/jacoco/jacoco.xml
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2                  # Sum both coverage parts into coverage/codeclimate.json
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json
  - cd commons-rest # goto library folder
  - mvn deploy -Dregistry=https://maven.pkg.github.com/rocketbase-io -Dtoken=$GH_TOKEN # push to github packages
## release on tag
deploy:
  - provider: script
    script: ".travis/deploy.sh"
    skip_cleanup: true
    on:
      tags: true

## disable emailing
#notifications:
#  email: false