language: java

jdk:
  - oraclejdk8

script: mvn --settings .travis/settings.xml clean verify

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: rocketbase-io/commons-rest
      tags: true
      jdk: oraclejdk8